version: '3'


services:
  redis:
    image: "redislabs/redismod:latest"
    ports:
      - "6379:6379"
  webapp:
    image: "maguec/dnszonegenerator:latest"
    links:
      - "redis:redis"
    ports:
      - "8080:8080"
    environment:
        - SESSION_REDIS=redis://@redis:6379
